apiVersion: apps/v1
kind: Deployment
metadata:
  name: roxstar-family-car-race
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roxstar-family-car-race
  template:
    metadata:
      labels:
        app: roxstar-family-car-race
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: user-pool
      containers:
        - name: roxstar-family-car-race
          image: ${AZURE_CONTAINER_REGISTRY}/roxstar-family-car-race:${IMAGE_TAG}
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=900"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: aws-test-secret
