apiVersion: v1
kind: Service
metadata:
  name: roxstar-family-car-race-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: roxstar-family-car-race
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
